onboarding = false

[theme]
name = "gruvbox"
auto_switch = false

[ui]
status_indicators = "symbols"
prompt_new_tab_name = false

[[keys.command]]
key = "prefix+f"
type = "plugin_action"
command = "herdr-navigator.open"
description = "jump to anything"

[[keys.command]]
key = "prefix+y"
type = "plugin_action"
command = "ray.file-explorer.open"
description = "yazi split"

[[keys.command]]
key = "prefix+Y"
type = "plugin_action"
command = "ray.file-explorer.open-tab"
description = "yazi tab"
