vim.keymap.set('n', '<F2>', ':w<Enter>', { noremap = true, silent = true })
vim.keymap.set('n', '<F4>', ':q<Enter>', { noremap = true, silent = true })
vim.keymap.set('n', '<F16>', ':q!<Enter>', { noremap = true, silent = true })
vim.keymap.set('i', '<F2>', '<ESC>:w<Enter>', { noremap = true, silent = true })
vim.keymap.set('i', '<F4>', '<ESC>:q<Enter>', { noremap = true, silent = true })
vim.keymap.set('i', '<F16>', '<ESC>:q!<Enter>', { noremap = true, silent = true })
vim.keymap.set('i', '<M-Up>', '<ESC>:m-2<Enter>i', { noremap = true, silent = true })
vim.keymap.set('i', '<M-Down>', '<ESC>:m+<Enter>i', { noremap = true, silent = true })
vim.keymap.set('i', '<S-Tab>', '<C-d>', { noremap = true, silent = true })
vim.keymap.set('v', '<F2>', ':w<Enter>', { noremap = true, silent = true })
vim.keymap.set('v', '<F4>', ':q<Enter>', { noremap = true, silent = true })
vim.keymap.set('v', '<F16>', ':q!<Enter>', { noremap = true, silent = true })
vim.keymap.set('v', '<M-Up>', '<ESC>:m-2<Enter>i', { noremap = true, silent = true })
vim.keymap.set('v', '<M-Down>', '<ESC>:m+<Enter>i', { noremap = true, silent = true })
vim.keymap.set('v', '<Tab>', '>gv', { noremap = true, silent = true })
vim.keymap.set('v', '<S-Tab>', '<gv', { noremap = true, silent = true })
vim.keymap.set('n', '<leader>n', ':NERDTreeFocus<CR>', { noremap = true, silent = true })
vim.keymap.set('n', '<C-t>', ':NERDTreeToggle<CR>', { noremap = true, silent = true })
vim.keymap.set('n', '<C-f>', ':NERDTreeFind<CR>', { noremap = true, silent = true })
local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, {})
vim.keymap.set('n', '<leader>fg', builtin.live_grep, {})
vim.keymap.set('n', '<leader>fb', builtin.buffers, {})
vim.keymap.set('n', '<leader>fh', builtin.help_tags, {})
